# Generated by Django 3.2 on 2021-05-29 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodywork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Кузов')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузовы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Марка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Марка (автомобиля/прицепа)',
                'verbose_name_plural': 'Марки (автомобиля/прицепа)',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Корзины пользователей',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Тип двигателя')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип двигателя',
                'verbose_name_plural': 'Типы двигателей',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Производитель шин',
                'verbose_name_plural': 'Производители шин',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(max_length=255, verbose_name='Модель')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('type_model', models.CharField(choices=[(None, 'Выберите тип модели'), ('car', 'Легковая'), ('truck', 'Прицеп/Полуприцеп')], default='car', max_length=20, verbose_name='Тип модели')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель (автомобиля/прицепа)',
                'verbose_name_plural': 'Модели (автомобиля/прицепа)',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(choices=[(None, 'Выберите способ доставки'), ('delivery_by', 'Доставка по Беларуси'), ('delivery_ru', 'Доставка в РФ'), ('pick_up', 'Самовывоз')], max_length=24, verbose_name='Доставка')),
                ('payment_type', models.CharField(choices=[(None, 'Выберите способ оплаты'), ('cash', 'Наличные'), ('card', 'Карта'), ('non_cash', 'Безналичный расчет (для юридических лиц)'), ('card_halva', 'Карта рассрочки «Халва»'), ('card_buy', '«Карта покупок» в рассрочку до 3 месяцев')], max_length=100, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('cancel', 'Заказ отменен')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('data_place', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('country', models.CharField(choices=[(None, 'Выберите страну'), ('Bel', 'Беларусь'), ('ru', 'Россия')], max_length=16, verbose_name='Страна')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('image', models.ImageField(default='default.png', upload_to='wheel', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('diameter', models.PositiveSmallIntegerField(verbose_name='Диаметр')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('pcd', models.CharField(max_length=255, verbose_name='PCD')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('article', models.CharField(db_index=True, max_length=120, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Диски',
                'verbose_name_plural': 'Диски',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('season', models.CharField(choices=[(None, 'Выберите сезон'), ('summer', 'Летний'), ('winter', 'Зимний'), ('all-season', 'Всесезонный')], max_length=20, verbose_name='Сезон')),
                ('diameter', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Диаметр')),
                ('width', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Ширина')),
                ('profile', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Профиль')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('article', models.CharField(db_index=True, max_length=120, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('image', models.ImageField(default='default.png', upload_to='tire', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Шины',
                'verbose_name_plural': 'Шины',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('chapter', models.CharField(choices=[(None, 'Выберите раздел'), ('car', 'Легковые'), ('semi-trailer', 'Полуприцепы'), ('trailer', 'Прицепы')], max_length=20, verbose_name='Раздел')),
                ('image', models.ImageField(default='default.png', upload_to='spare_parts', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('article', models.CharField(db_index=True, max_length=120, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Содержимое в заказе',
                'verbose_name_plural': 'Содержимое в заказе',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KitCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description – это одиночный тег, содержащий краткое описание web-страницы, используемое при формировании сниппета. Данный тег в значительной степени влияет на представление сайта в результатах поисковой выдачи, и рекомендуется к заполнению поисковыми системами.', null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords — список ключевых слов , соответствующих содержимому страницы сайта.', null=True, verbose_name='Meta Keywords')),
                ('image', models.ImageField(default='default.png', upload_to='kit-car', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя')),
                ('transmission', models.CharField(choices=[(None, 'Выберите коробку передач'), ('mechanics', 'Механика'), ('automatic', 'Автомат')], max_length=10, verbose_name='Коробка передач')),
                ('drive', models.CharField(choices=[(None, 'Выберите привод'), ('front', 'Передний привод'), ('rear_drive', 'Задний привод')], max_length=32, verbose_name='Привод')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('vin', models.CharField(max_length=255, unique=True, verbose_name='VIN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('bodywork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bodywork', verbose_name='Кузов')),
                ('engine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.enginetype', verbose_name='Тип двигателя')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Машинокомплект',
                'verbose_name_plural': 'Машинокомплекты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CartContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='Корзина пользователя')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Содержимое в корзине',
                'verbose_name_plural': 'Содержимое в корзине',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='additional_photos', verbose_name='Фотография')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
                'ordering': ['-id'],
            },
        ),
    ]
