# Generated by Django 3.2 on 2021-05-29 15:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('car', 'Автомобили'), ('truck', 'Прицеп/Полуприцеп')], default='car', help_text='Выберите одну или несколько подкатегорий', max_length=9, verbose_name='Покатегория'),
            preserve_default=False,
        ),
    ]
