# Generated by Django 3.2 on 2021-04-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ['title'], 'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['title'], 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='autopart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='autopart',
            name='image',
            field=models.ImageField(null=True, upload_to='auto_parts', verbose_name='Фотография'),
        ),
    ]
