# Generated by Django 3.2 on 2021-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='type_model',
            field=models.CharField(choices=[(None, 'Выберите тип модели'), ('car', 'Грузовые'), ('truck', 'Прицеп/Полуприцеп')], max_length=20, verbose_name='Тип модели'),
        ),
    ]
