# Generated by Django 3.2 on 2021-06-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sparepart_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='diameter',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Диаметр'),
        ),
    ]
