# Generated by Django 3.2 on 2021-06-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_wheel_diameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='article',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='year',
            field=models.PositiveSmallIntegerField(default=1990, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
