# Generated by Django 3.2 on 2021-06-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210617_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год'),
        ),
    ]
