# Generated by Django 3.2 on 2021-04-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='wheel_drive', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('diameter', models.CharField(max_length=255, verbose_name='Диаметр')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('pcd', models.CharField(max_length=255, verbose_name='PCD')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('article', models.CharField(db_index=True, max_length=120, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carmodel', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Диски',
                'verbose_name_plural': 'Диски',
                'ordering': ['-id'],
            },
        ),
    ]
