# Generated by Django 3.2 on 2021-06-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_sparepart_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
