# Generated by Django 3.2 on 2021-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wheeldrive_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='wheeldrive',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
    ]
