# Generated by Django 3.2 on 2021-04-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_additionalphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopart',
            name='title',
        ),
    ]
