# Generated by Django 3.2 on 2021-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopart',
            name='article',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=255, unique=True, verbose_name='VIN'),
        ),
    ]
