# Generated by Django 3.2 on 2021-05-01 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_auto_20210429_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(choices=[(None, 'Выберите способ доставки'), ('delivery', 'Доставка'), ('pick_up', 'Самовывоз')], max_length=24, verbose_name='Доставка')),
                ('payment_type', models.CharField(choices=[(None, 'Выберите способ оплаты'), ('cash', 'Наличные'), ('card', 'Карта'), ('non_cash', 'Безналичный расчет (для юридических лиц)'), ('card_halva', 'Карта рассрочки «Халва»'), ('card_buy', '«Карта покупок» в рассрочку до 3 месяцев')], max_length=100, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('cancel', 'Заказ отменен')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('data_place', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('address_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.addressuser', verbose_name='Пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id'],
            },
        ),
    ]
