# Generated by Django 3.2 on 2021-05-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0017_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.addressuser', verbose_name='Адрес доставки'),
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Содержимое в заказе',
                'verbose_name_plural': 'Содержимое в заказе',
                'ordering': ['-id'],
            },
        ),
    ]
