# Generated by Django 3.2 on 2021-05-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0018_auto_20210503_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.addressuser', verbose_name='Адрес доставки'),
        ),
    ]
