# Generated by Django 3.2 on 2021-05-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0019_alter_order_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.addressuser', verbose_name='Адрес доставки'),
        ),
    ]
