# Generated by Django 3.2 on 2021-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_car_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя'),
        ),
    ]
