# Generated by Django 3.2 on 2021-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_car_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheeldrive',
            name='diameter',
            field=models.PositiveSmallIntegerField(verbose_name='Диаметр'),
        ),
    ]
